version: '3.7'

services:
  app:
    # create image from Dockerfile
    build:
      context: .
      target: development
    environment:
      USE_TEST_DB: 'true'
    # container will run our server through nodeamon
    command: yarn start:dev
    ports:
      - 3000:3000
    # bind cwd with our image workdir /srv/app
    volumes:
      - .:/srv/app:delegated
    depends_on:
      - db
    restart: always
    networks:
      - meeting-planner-network

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: letsmeet
      MYSQL_DATABASE: meetingplanner
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      - ./utils/test_db.sql:/docker-entrypoint-initdb.d/test_db.sql
    restart: always
    networks:
      - meeting-planner-network

networks:
  meeting-planner-network:
    driver: bridge
